//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 11:11:11 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jonwelzel.com/hellossl/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jonwelzel.hellossl.xml;
